name: Sync Version & Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      # Sync the version number again
      - name: Sync version
        run: |
          npm version ${GITHUB_REF_NAME#v} --no-git-tag-version

      - run: npm ci
      
      - run: npm publish --provenance --access public
